{"uuid": "61d308bb-0534-4b62-bd61-805f30bd6382", "children": ["b8f2f1d6-bf57-4690-993c-0a552ad897cc"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "RuntimeError: 浏览器启动失败: Could not reach host. Are you offline?\n", "trace": "  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 681, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\tests\\conftest.py\", line 7, in browser\n    driver = browser.start_browser()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\core\\browser_manager.py\", line 113, in start_browser\n    raise RuntimeError(f\"浏览器启动失败: {str(e)}\")\n"}, "start": 1754633694755, "stop": 1754633712326}], "start": 1754633694755, "stop": 1754633712454}